version: '3.4'
services:
  snapclient:
    image: ivdata/snapclient
    container_name: ${APP}-snapclient
    environment:
      HOST: snapserver
    devices:
      - /dev/snd
      - /dev/bus/usb
    command: /bin/bash -c /usr/bin/snapclient -h snapserver -s 1
  snapserver:
    image: cristianpb/snapserver
    container_name: ${APP}-snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - ${HOST_SNAPCAST_TEMP}:/tmp
      #- ./snapcast/snapserver.conf:/etc/default/snapserver.conf
  mopidy:
    image: ${DOCKER_USERNAME}/${APP}:${APP_VERSION_CUT}
    container_name: ${APP}
    build:
      context: .
      dockerfile: Dockerfile
      target: muse
      args:
        app_path: /${APP}
    depends_on:
      - snapserver
    ports:
      - 6680:6680
    volumes:
      - ./__sapper__/export/muse:/${APP}/mopidy_muse/static
      - ./mopidy_muse/mopidy.conf:/root/.config/mopidy/mopidy.conf
      - ${HOST_MUSIC_DIRECTORY}:/var/lib/mopidy/music
      - ${HOST_PLAYLIST_DIRECTORY}:/var/lib/mopidy/playlists
      - ${HOST_SNAPCAST_TEMP}:/tmp
      - ${APP_PATH}/dist:/${APP}/dist
