FROM ubuntu:bionic AS snapcast

RUN apt-get update \
 && apt-get -y install build-essential curl git libasound2-dev libboost-dev libopus-dev libvorbisidec-dev libvorbis-dev libflac-dev alsa-utils libavahi-client-dev avahi-daemon libsoxr-dev \
 && apt-get clean && rm -fR /var/lib/apt/lists

ARG SNAPCAST_VERSION=0.25.0
ARG BOOST_VERSION=1.76.0
ARG BOOST_VERSION_UNDERSCORED=1_76_0

RUN cd /tmp \
 && curl -L -o boost_${BOOST_VERSION_UNDERSCORED}.tar.gz  https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION_UNDERSCORED}.tar.gz \
 && tar xzf boost_${BOOST_VERSION_UNDERSCORED}.tar.gz \
 && git clone --single-branch --branch v${SNAPCAST_VERSION} https://github.com/badaix/snapcast.git \
 && cd snapcast \
 && git submodule update --init --recursive \
 && ADD_CFLAGS="-I/tmp/boost_${BOOST_VERSION_UNDERSCORED}" make -C server \
 && cp server/snapserver /usr/local/bin/ \
 && cp server/etc/snapserver.conf /etc/ \
 && cd .. \
 && rm snapcast boost_${BOOST_VERSION_UNDERSCORED} -fR

FROM ubuntu:bionic as prod

RUN if [ "$TARGETARCH" = "arm64" ] ; then \
        apt-get update && \
        apt-get -y install curl libportaudio2 libvorbis0a libavahi-client3 libflac8 libvorbisenc2 libvorbisfile3 libopus0 libsoxr0 && \
        apt-get clean && rm -fR /var/lib/apt/lists; \
   fi ;

COPY --from=snapcast /usr/local/bin/snapserver /usr/local/bin/
COPY --from=snapcast /etc/snapserver.conf /etc/

RUN if [ "$TARGETARCH" = "amd64" ] ; then \
        rm -rf /usr/local/bin/snapserver && \
        rm -rf /etc/snapserver.conf && \
        apt-get update && \
        apt-get install -y --no-install-recommends ca-certificates curl libasound2 mpv && \
        curl -L -o /tmp/snapserver.deb "https://github.com/badaix/snapcast/releases/download/v${SNAPCAST_VERSION}/snapserver_${SNAPCAST_VERSION}-1_${TARGETARCH}.deb" && \
        dpkg -i /tmp/snapserver.deb || apt-get install -f -y --no-install-recommends && \
        apt-get clean && rm -fR /var/lib/apt/lists; \
    fi ;

CMD ["snapserver"]

ENV DEVICE_NAME=Snapcast
EXPOSE 1704/tcp 1705/tcp 1780/tcp

# vim:filetype=dockerfile
